# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d001c9129ad00878b859552bc3743dfdeedf0b19c4762ac7f5e6488425cf5368fe27453c2e3097e0077b407001e4f1ad40ac6781ad34a8d223487ee2e06a56c8

test:
  secret_key_base: 8e38e21d89b1fcf10c2bdd7f2db1d42abcd0770030f2302e9630d9eed784a6423d6aef74fc65476e8df2a55416b1d25b5114a91518900f34c7e76c68fdc90081

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
